apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-container
  template:
    metadata:
      labels:
        app: backend-container
    spec:
      containers:
        - name: backend
          image: chahidhadifi/my-backend-image:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-container
spec:
  ports:
    - port: 8080
  selector:
    app: backend-container
