apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
        - name: frontend
          image: chahidhadifi/my-frontend-image:latest
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-container
spec:
  type: NodePort
  ports:
    - port: 5173
      nodePort: 30001 
  selector:
    app: frontend-container
