version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-container
    env_file:
      - ./backend/sms/.env.list
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: localhost:5000/my-backend-image:latest
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my-network

  frontend:
    image: localhost:5000/my-frontend-image:latest
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge
