services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-cors
    ports:
      - "5001:5000"
    volumes:
      - ../util/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registry
    restart: always

  ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - "8081:80"
    environment:
      - REGISTRY_URL=http://localhost:5001
      - REGISTRY_TITLE=Mon Registre Privé
    depends_on:
      - registry
      - nginx
    restart: always

volumes:
  registry-data:
