apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: exam
data:
  SPRING_APPLICATION_NAME: sms
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/sms_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: chahidhadifi
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_SHOW_SQL: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: exam
data:
  POSTGRES_DB: sms_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: chahidhadifi
