apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: exam
type: Opaque
data:
  POSTGRES_PASSWORD: Y2hhaWRoYWRpZmk=  # "chahidhadifi" encodé en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: exam
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: Y2hhaWRoYWRpZmk=  # "chahidhadifi" encodé en base64
---
