apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    myapp: ["superuser", "createdb"]
  databases:
    myappdb: myapp
  postgresql:
    version: "14"
